name: pureair
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_bloc: ^5.0.0
  bloc: ^5.0.0
  auto_size_text: ^2.1.0
  http: ^0.12.1
  intl: ^0.16.1
  equatable: ^1.2.0
  meta: ^1.1.8
  path_provider: ^1.6.11
  flutter_offline: ^0.3.0
  connectivity: ^0.4.9
  geocoder: ^0.2.1
  simple_animations: ^2.2.1
  pull_to_refresh: ^1.6.0
  response: ^0.1.1
  sliding_up_panel: ^1.0.2
  flutter_launcher_icons: ^0.7.5
  autocomplete_textfield: ^1.7.3
  fl_chart: ^0.10.1
  google_maps_flutter: ^0.5.28+1
  flutter_google_places: ^0.2.5
  location: ^3.0.2
  latlong: ^0.6.1
  geolocator:
  intl_translation:
  json_annotation:
  rxdart:
  path:
  sembast:
  sticky_headers:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:

dependency_overrides:
  flutter_offline: ^0.3.0
  connectivity: ^0.4.9

flutter_icons:
  image_path: 'assets/images/appicon.png'
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/icon-exercise.png
    - images/icon-avoid-exercise.png
    - images/icon-window.png
    - images/icon-mask.png
    - images/icon-globe.png
    - images/icon-close-windows.png
    - images/menu.png
    - images/unhealthy.png
    - images/very-unhealthy.png
    - images/home-filled.png
    - images/home.png
    - images/search-filled.png
    - images/search.png
    - images/settings-filled.png
    - images/settings.png
    - images/water.png
    - images/location.png
    - images/plume-labs-2.jpg
    - images/arrows.png
    - images/cloud.png
    - images/drop.png
    - images/umbrella.png
    - images/wind.png
    - images/park.png
    - images/heart.png
    - images/cycling.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ProductSans
      fonts:
        - asset: fonts/ProductSans-Black.ttf
        - asset: fonts/ProductSans-Bold.ttf
        - asset: fonts/ProductSans-Light.ttf
        - asset: fonts/ProductSans-Thin.ttf
        - asset: fonts/ProductSans-Regular.ttf
        - asset: fonts/ProductSans-Medium.ttf 
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
